---
- name: SDS installation
  hosts: sds
  vars_files:
    - ../../../../playbooks/roles/vars_files/connection.yml
  tasks:
    - name: Install common packages
      ansible.builtin.import_role:
        name: powerflex_common
      vars:
        powerflex_sds_state: present

    - name: Install and configure powerflex SDS
      ansible.builtin.import_role:
        name: powerflex_sds
      vars:
        powerflex_sds_state: present

    - name: Verifying device in normal mode
      ansible.builtin.assert:
        that:
          - powerflex_sds_add_device_output.device_details.mediaType == "{{ powerflex_sds_device_media_type }}"
          - powerflex_sds_add_device_output.device_details.name == "{{ powerflex_sds_device_name }}"
          - powerflex_sds_add_device_output.device_details.externalAccelerationType == "{{ powerflex_sds_external_acceleration_type }}"
          - powerflex_sds_add_device_output.device_details.storagepoolPoolName == "{{ powerflex_sds_storage_pool }}"
          - powerflex_sds_add_device_output.device_details.protectionDomainName == "{{ powerflex_sds_protection_domain }}"
      when:
        - not ansible_check_mode
        - powerflex_sds_add_device_output.changed

    - name: Verifying install package in check mode
      ansible.builtin.assert:
        that:
          - powerflex_common_install_package_output.msg == "Check mode: No changes made"
      when: ansible_check_mode

    - name: Verifying installation package
      ansible.builtin.assert:
        that:
          - " 'Installed' in powerflex_common_install_package_output.results[0]"
      when:
        - not ansible_check_mode
        - powerflex_common_install_package_output.changed

    - name: Verifying device in Idempotency
      ansible.builtin.assert:
        that:
          - powerflex_sds_add_device_output.device_details.mediaType == "{{ powerflex_sds_device_media_type }}"
          - powerflex_sds_add_device_output.device_details.name == "{{ powerflex_sds_device_name }}"
          - powerflex_sds_add_device_output.device_details.externalAccelerationType == "{{ powerflex_sds_external_acceleration_type }}"
          - powerflex_sds_add_device_output.device_details.storagepoolPoolName == "{{ powerflex_sds_storage_pool }}"
          - powerflex_sds_add_device_output.device_details.protectionDomainName == "{{ powerflex_sds_protection_domain }}"
      when:
        - not ansible_check_mode
        - not powerflex_sds_add_device_output.changed
