---
- name: Molecule Test for installation of LIA with invalid rpm path, rpm file
  hosts: lia
  vars_files:
    - ../../../../playbooks/roles/vars_files/connection.yml

  tasks:
    - name: Install and configure powerflex LIA with no rpm
      ansible.builtin.import_role:
        name: powerflex_lia
      vars:
        powerflex_common_file_install_location: "/opt/empty"
        powerflex_lia_state: present
      register: powerflex_lia_no_rpm_result
      ignore_errors: true

    - name: Verifying failure of install package with respect to no rpm file in normal mode
      ansible.builtin.assert:
        that:
          - powerflex_common_package_file.files | length | int == 0

    - name: Install and configure powerflex lia with wrong file path
      ansible.builtin.import_role:
        name: powerflex_lia
      vars:
        powerflex_common_file_install_location: "/opt/aaab"
        powerflex_lia_state: present
      register: powerflex_lia_wrong_file_path_result
      ignore_errors: true

    - name: Verifying failure of install package with wrong file path in normal mode
      ansible.builtin.assert:
        that:
          - powerflex_common_package_file.files | length | int == 0
