---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    volumes:
      - /tmp:/tmp
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../../../playbooks/roles/inventory
      group_vars: ../../../../playbooks/roles/group_vars/
      host_vars: ../../../../playbooks/roles/host_vars/
verifier:
  name: ansible
scenario:
  test_sequence:
    - check
    - converge
    - idempotence
