---
- name: Molecule Test for installation of SDR with invalid rpm path, rpm file
  hosts: sdr
  vars_files:
    - ../../../../playbooks/roles/vars_files/connection.yml

  tasks:
    - name: Install and configure powerflex SDR with no rpm
      ansible.builtin.import_role:
        name: powerflex_sdr
      vars:
        powerflex_common_file_install_location: "/opt/empty"
        powerflex_sdr_state: present
      register: powerflex_sdr_no_rpm_result
      ignore_errors: true

    - name: Verifying failure of install package with respect to no rpm file in normal mode
      ansible.builtin.assert:
        that:
          - powerflex_common_package_file.files | length | int == 0

    - name: Install and configure powerflex SDR with wrong file path
      ansible.builtin.import_role:
        name: powerflex_sdr
      vars:
        powerflex_common_file_install_location: "/opt/aaab"
        powerflex_sdr_state: present
      ignore_errors: true
      register: powerflex_sdr_wrong_path_result

    - name: Verifying failure of install package with wrong file path
      ansible.builtin.assert:
        that:
          - powerflex_common_package_file.files | length == 0
