---
- name: Install gateway
  hosts: gateway
  gather_facts: true
  tasks:
    - name: Install and configure powerflex gateway
      ansible.builtin.import_role:
        name: "powerflex_gateway"
      vars:
        powerflex_gateway_state: present
      register: powerflex_gateway_result_molecule

    - name: Verifying installation package in check mode
      ansible.builtin.assert:
        that:
          - " 'No changes made, but would have if not in check mode' in powerflex_common_install_package_output.msg"
      when: ansible_check_mode

    - name: Verifying installation package
      ansible.builtin.assert:
        that:
          - " 'Installed' in powerflex_common_install_package_output.results[0]"
      when: not ansible_check_mode and powerflex_common_install_package_output.changed

    - name: Verifying installation package in idempotency
      ansible.builtin.assert:
        that:
          - " 'Nothing to do' in powerflex_common_install_package_output.msg"
      when: not ansible_check_mode and not powerflex_common_install_package_output.changed
