---
- name: "Install PowerFlex Common"
  hosts: all
  roles:
    - powerflex_common

- name: Install and configure PowerFlex ActiveMQ
  hosts: activemq
  vars_files:
    - vars_files/connection.yml
  roles:
    - powerflex_activemq

- name: Install and configure PowerFlex LIA
  hosts: lia
  vars_files:
    - vars_files/connection.yml
  roles:
    - powerflex_lia

- name: Install and configure PowerFlex MDM
  hosts: mdm
  roles:
    - powerflex_mdm

- name: Install and configure PowerFlex TB
  hosts: tb
  vars_files:
    - vars_files/connection.yml
  roles:
    - powerflex_tb

- name: Configure protection domain, fault set and storage pool.
  hosts: config
  vars_files:
    - vars_files/connection.yml
  roles:
    - powerflex_config

- name: Install and configure PowerFlex SDC
  hosts: sdc
  vars_files:
    - vars_files/connection.yml
  roles:
    - powerflex_sdc

- name: Install and configure PowerFlex SDS
  hosts: sds
  vars_files:
    - vars_files/connection.yml
  roles:
    - powerflex_sds

- name: Install PowerFlex SDR
  hosts: sdr
  vars_files:
    - vars_files/connection.yml
  roles:
    - powerflex_sdr

- name: Install and configure PowerFlex SDT
  hosts: sdt
  vars_files:
    - vars_files/connection.yml
  roles:
    - powerflex_sdt
