---
- name: Converge
  hosts: webui
  vars_files:
    - ../../../../playbooks/roles/vars_files/connection.yml
  gather_facts: true
  tasks:
    - name: Uninstall powerflex webui
      ansible.builtin.import_role:
        name: "powerflex_webui"
      vars:
        powerflex_webui_state: 'absent'

    - name: Verifying uninstall package in converge
      ansible.builtin.assert:
        that:
          - " 'Removed:' in powerflex_webui_uninstall_output.results[0].results[0]"
      when: not ansible_check_mode and powerflex_webui_uninstall_output.changed and ansible_distribution in ("RedHat", "CentOS", "SLES")

    - name: Verifying uninstall package in check mode
      ansible.builtin.assert:
        that:
          - powerflex_webui_uninstall_output.results[0].msg == "Check mode: No changes made, but would have if not in check mode"
      when: ansible_check_mode and ansible_distribution in ("RedHat", "CentOS", "SLES")

    - name: Verifying uninstall package in Idempotency
      ansible.builtin.assert:
        that:
          - powerflex_webui_uninstall_output.results[0].msg == 'Nothing to do'
      when: not ansible_check_mode and not powerflex_webui_uninstall_output.changed and ansible_distribution in ("RedHat", "CentOS", "SLES")

    - name: Verifying uninstall package in check mode for deb
      ansible.builtin.assert:
        that:
          - powerflex_webui_uninstall_deb_output.results[0].msg == "Check mode: No changes made, but would have if not in check mode"
      when: ansible_check_mode and ansible_distribution == "Ubuntu"

    - name: Verifying uninstall package in converge for deb
      ansible.builtin.assert:
        that:
          - " 'Removed:' in powerflex_webui_uninstall_deb_output.results[0].results[0]"
      when: not ansible_check_mode and powerflex_webui_uninstall_deb_output.changed and ansible_distribution == "Ubuntu"

    - name: Verifying uninstall package in Idempotency for deb
      ansible.builtin.assert:
        that:
          - powerflex_webui_uninstall_deb_output.results[0].msg == 'Nothing to do'
      when: not ansible_check_mode and not powerflex_webui_uninstall_deb_output.changed and ansible_distribution == "Ubuntu"
