---
- name: Snapshot V2 Operations
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    hostname: 'x.x.x.x'
    username: 'admin'
    password: 'Password'
    validate_certs: false
    # Use unique names
    vol_name: "ansible_snap_vol"
    snap_name: "ansible_snapshot"
    snap_new_name: "ansible_snap_rn"

  tasks:
    - name: Create source volume
      register: vol_result
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_name: "{{ vol_name }}"
        storage_pool_name: "{{ storage_pool_name }}"
        protection_domain_name: "{{ protection_domain_name }}"
        size: 8
        state: "present"

    - name: Set volume id
      set_fact:
        vol_id: "{{ vol_result.volume_details.id }}"

    - name: Create snapshot
      register: result
      dellemc.powerflex.snapshot_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        snapshot_name: "{{ snap_name }}"
        vol_name: "{{ vol_name }}"
        state: "present"

    - name: Set snapshot id
      ansible.builtin.set_fact:
        snapshot_id: "{{ result.snapshot_details.id }}"

    - name: Get snapshot details using snapshot id
      dellemc.powerflex.snapshot_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        snapshot_id: "{{ snapshot_id }}"
        state: "present"

    - name: Rename snapshot
      dellemc.powerflex.snapshot_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        snapshot_id: "{{ snapshot_id }}"
        snapshot_new_name: "{{ snap_new_name }}"
        state: "present"

    - name: Delete snapshot
      dellemc.powerflex.snapshot_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        snapshot_id: "{{ snapshot_id }}"
        remove_mode: "ONLY_ME"
        state: "absent"

    - name: Delete source volume
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
        state: "absent"
