---
- name: Volume operations on powerflex array.
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    hostname: '10.247.39.166'
    username: 'admin'
    password: 'Password123!'
    validate_certs: false
    protection_domain_name: "destiny-PD"
    storage_pool_name: "destiny-SP1"
    vol_name: "sample_ansible_volume_20"

  tasks:
    - name: Create a volume
      register: result
      dellemc.powerflex.volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_name: "{{ vol_name }}"
        storage_pool_name: "{{ storage_pool_name }}"
        protection_domain_name: "{{ protection_domain_name }}"
        size: 8
        state: "present"

    - name: Set volume id
      ansible.builtin.set_fact:
        vol_id: "{{ result.volume_details.id }}"

    - name: Get volume details using volume id
      dellemc.powerflex.volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
        state: "present"

    - name: Get volume details using volume name
      dellemc.powerflex.volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_name: "{{ vol_name }}"
        state: "present"

    - name: Modify the size
      dellemc.powerflex.volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_name: "{{ vol_name }}"
        size: 16
        state: "present"

    - name: Map volume to SDC and remove snapshot policy
      dellemc.powerflex.volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
        state: "present"

    - name: Modify the attributes of SDC mapped to volume
      dellemc.powerflex.volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
        state: "present"

    - name: Unmap SDCs from volume
      dellemc.powerflex.volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
