---
- name: Volume operations on powerflex array.
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    hostname: 'x.x.x.x'
    username: 'admin'
    password: 'Password'
    validate_certs: false
    # Use unique names and existing Tundra resources
    vol_name: "ansible_vol"
    vol_new_name: "ansible_vol_rn"

  tasks:
    - name: Create a volume
      register: result
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_name: "{{ vol_name }}"
        storage_pool_name: "{{ storage_pool_name }}"
        protection_domain_name: "{{ protection_domain_name }}"
        size: 8
        state: "present"

    - name: Set volume id
      ansible.builtin.set_fact:
        vol_id: "{{ result.volume_details.id }}"

    - name: Get volume details using volume id
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
        state: "present"

    - name: Get volume details using volume name
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_name: "{{ vol_name }}"
        state: "present"

    - name: Modify the size
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_name: "{{ vol_name }}"
        size: 16
        state: "present"

    - name: Map volume to SDC
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
        sdc:
          - sdc_ip: "{{ sdc_ip }}"
        allow_multiple_mappings: true
        sdc_state: "mapped"
        state: "present"

    - name: Unmap SDC from volume
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
        sdc:
          - sdc_ip: "{{ sdc_ip }}"
        sdc_state: "unmapped"
        state: "present"

    - name: Rename volume
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
        vol_new_name: "{{ vol_new_name }}"
        state: "present"

    - name: Delete volume
      dellemc.powerflex.volume_v2:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vol_id: "{{ vol_id }}"
        state: "absent"
