---
- name: Uninstall package
  register: powerflex_lia_uninstall_output
  environment:
    I_AM_SURE: "{{ i_am_sure | int }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "absent"
  with_items:
    - EMC-ScaleIO-lia
  when: ansible_distribution in ("RedHat", "CentOS", "SLES")

- name: Uninstall deb package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - emc-scaleio-lia
  when: ansible_distribution == "Ubuntu"
